### ISSUE TITLE
sokol-shdc TODO

### ISSUE THREAD

**Issue by floooh** [floooh/sokol-tools#8]
- [ ] investigate how the new SPIRV-Cross #line information can be improved with SPIRV-Tools optimizer passes enabled (e.g. which passes mangle the location the worst)
- [ ] alternatively have a "dev-mode" where the optimizer passes don't run (because then the line infos appear perfect)
- [ ] implement the #line mapping for D3D... check if the D3D compiler actually uses the #line info for errors and warnings, otherwise parse the #line statements myself

**Comment by mattiasljungstrom** [comment]
What if on error you compile the shader again with all optimizations turned off to get the line nrs?

**Comment by floooh** [comment]
Good idea!

**Comment by eugeneko** [comment]
Is it possible to publish `sokol-shdc` as library?
It's useful tool, but I don't want to have process interop unless necessary.
So I'd like to statically link against `sokol-shdc` and have some basic interface that will let me use it without unnecessary I/O (e.g. if I don't want to save compiled shader).

**Comment by floooh** [comment]
It's possible (main.c would need to be replaced with a sokol_shdc.h/.c, which implements a small API to pass options but otherwise looks much like main.c).

But I think the required dependencies would make this tricky / pretty big (the stuff in here would need to be linked in basically: https://github.com/floooh/sokol-tools/tree/master/ext).

Also the bytecode-compilation for D3D11 and especially Metal should be removed, this is better done via sokol_gfx.h then (especially because compiling Metal bytecode involves running the metal-compiler command line tool as external process).

**Comment by eugeneko** [comment]
I'm mostly interested in pure GLSL->HLSL, GLSL, Metal conversion and maybe shader optimization.
This is the most re-usable and generic part of this tool.
May you give me a hint what files in `shdc` are responsible for this logic?

**Comment by floooh** [comment]
Here's a quick explanation what each source file is responsible for:

- args.cc: pass command line arguments into an args_t object
- input.cc: load and parse the GLSL source file into an input_t object
- spirv.cc: wrapper around https://github.com/KhronosGroup/glslang to compile vertex- and fragment-shader snippets into SPIRV, results in a number of populated spirv_t objects
- spirvcross.cc: wrapper around https://github.com/KhronosGroup/SPIRV-Cross to translate the generated SPIRV bytecode to the target shader languages, results in a number of populated spirvcross_t objects
- bytecode.cc: optionally compile HLSL and/or Metal shader source code to bytecode via d3dcompiler.dll and/or invoking the macOS/iOS Metal shader compiler as command line tool, results in a number of bytecode_t objects
- sokol.cc, bare.cc: these are the output file writers, sokol.cc generates a sokol_gfx.h compatible header, bare.cc generates binary files which can be loaded at runtime (more file writers may be added in the future)
